const path = {
  PUBLIC: "/",
  HOME: "",
  LOGIN: "login",
  SIGNUP: "signup",
  BLOGS: "blogs",
  PRODUCTS: "products",
  CATEGORY: "products/:category",
  SERVICES: "services",
  USER: "user",
  CART: "cart",
  PAYMENT: "cart/payment-infos",
  SEARCH: "search",
  FAQS: "faqs",
  ADMIN: "admin",
  ECOMMERCE: "ecommerce",
  ORDERS: "orders",
  CUSTOMERS: "customers",
  EMPLOYEES: "employees",
  BLOGS_ADMIN: "blogs-control",
  CALENDAR: "calendar",
  SETTINGS: "settings",
  AREA: "area",
  BAR: "bar",
  FINANCIAL: "financial",
  LINE: "line",
  PIE: "pie",
  PYRAMID: "pyramid",
  STACKED: "stacked",
  CHAT: "chat",
  DETAILS_PRODUCT: "products/:category/:title/:id",
  ALL: "*",
};

export default path;
